package com.payscope.employee;

public enum Role {
    SOFTWARE_ENGINEER, DATA_ENGINEER, PRODUCT_MANAGER, DESIGNER, ACCOUNT_EXECUTIVE,
    MARKETING_MANAGER, ACCOUNTANT, RECRUITER, SUPPORT_SPECIALIST
}
